name: ASH SAST Scan

on:
  push:
    branches: [ '**' ]

env:
  ASH_OUTPUT_PATH: ash_output

jobs:
  containerjob:
    name: Run ASH Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ASH
        uses: actions/checkout@v4
        with:
          path: ./automated-security-helper
          repository: awslabs/automated-security-helper
          ref: v1.3.3
      - name: Checkout app repo
        uses: actions/checkout@v4
        with:
          path: ./repo
      - name: Run ASH scan against repo
        run: |
          export PATH="$(pwd)/automated-security-helper:$PATH"

          ash \
            --source-dir "$(pwd)/repo" \
            --output-dir "${{ env.ASH_OUTPUT_PATH }}"

      - name: Publish ${{ env.ASH_OUTPUT_PATH }}
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: ${{ env.ASH_OUTPUT_PATH }}
          path: ${{ env.ASH_OUTPUT_PATH }}
