name: Yor GitHub Action

on:
  push:
    branches:
      - main

jobs:
  yor-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run yor action
        uses: bridgecrewio/yor-action@0.3.0
